2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_setup.py:_flush():68] Configure stats pid to 488657
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_setup.py:_flush():68] Loading settings from /home/ai/.config/wandb/settings
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_setup.py:_flush():68] Loading settings from /home/ai/DI725_assignment1-main/wandb/settings
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_init.py:_log_setup():528] Logging user logs to /home/ai/DI725_assignment1-main/wandb/run-20250408_143541-af4600kn/logs/debug.log
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ai/DI725_assignment1-main/wandb/run-20250408_143541-af4600kn/logs/debug-internal.log
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_init.py:init():644] calling init triggers
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'out_dir': 'out-sentiment', 'eval_interval': 50, 'log_interval': 10, 'eval_iters': 20, 'eval_only': False, 'always_save_checkpoint': True, 'init_from': 'scratch', 'wandb_log': True, 'wandb_project': 'sentiment-analysis', 'wandb_run_name': 'gpt-sentiment-scratch', 'dataset': 'customer_service', 'gradient_accumulation_steps': 1, 'batch_size': 32, 'block_size': 512, 'n_layer': 4, 'n_head': 8, 'n_embd': 256, 'dropout': 0.2, 'bias': False, 'learning_rate': 2e-05, 'max_iters': 1000, 'weight_decay': 0.1, 'beta1': 0.9, 'beta2': 0.999, 'grad_clip': 1.0, 'decay_lr': True, 'warmup_iters': 100, 'lr_decay_iters': 800, 'min_lr': 2e-06, 'backend': 'nccl', 'device': 'cuda', 'dtype': 'bfloat16', 'compile': False}
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_init.py:init():680] starting backend
2025-04-08 14:35:41,300 INFO    MainThread:488657 [wandb_init.py:init():684] sending inform_init request
2025-04-08 14:35:41,345 INFO    MainThread:488657 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-08 14:35:41,345 INFO    MainThread:488657 [wandb_init.py:init():697] backend started and connected
2025-04-08 14:35:41,346 INFO    MainThread:488657 [wandb_init.py:init():790] updated telemetry
2025-04-08 14:35:41,346 INFO    MainThread:488657 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-04-08 14:35:41,678 ERROR   MainThread:488657 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-04-08 14:35:41,678 ERROR   MainThread:488657 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/ai/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/home/ai/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-04-08 14:35:41,693 WARNING MsgRouterThr:488657 [router.py:message_loop():75] message_loop has been closed
